### ISSUE TITLE
运行jd.py找不到文件

### ISSUE THREAD

**Issue by creazytom** [kallydev/privacy#1]
./jd.py
2020-11-28 13:01:33 INFO start scanning file lines
Traceback (most recent call last):
  File "./jd.py", line 112, in <module>
    converter.start()
  File "./jd.py", line 69, in start
    with open(self.file_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'www_jd_com_12g.txt'
#jd的txt文件放进了database文件夹里了，没有找到

**Comment by kallydev** [comment]
疏忽导致在文档里写错了，你把 txt 文件和 py 脚本放在同一目录下就行。因为我临时把路径和文件名都写死了，你可以先自己改改脚本里的 txt 路径参数，明天我再重构这些脚本。

**Comment by creazytom** [comment]
512m的罗马尼亚大盘鸡能跑的起来吗

**Comment by southcat** [comment]
> 512m的罗马尼亚大盘鸡能跑的起来吗

我在试512m的buyvm鸡导入数据

**Comment by kallydev** [comment]
> 512m的罗马尼亚大盘鸡能跑的起来吗

我看了一下示例网站的进程内存占用为 4M，主要还是和 IO 有关吧。索引都是储存在硬盘上的，预计问题不大。

**Comment by creazytom** [comment]
> > 512m的罗马尼亚大盘鸡能跑的起来吗
> 
> 我在试512m的buyvm鸡引入数据

我的罗马尼亚鸡还得过几天才能开通，开了一个vultr试试

**Comment by creazytom** [comment]
> > 512m的罗马尼亚大盘鸡能跑的起来吗
> 
> 我看了一下示例网站的进程内存占用为 4M，主要还是和 IO 有关吧。索引都是储存在硬盘上的，预计问题不大。

我把jd.py放到database里面运行，不能打开数据库文件
 ./jd.py
2020-11-28 13:34:57 INFO start scanning file lines
2020-11-28 13:38:33 INFO scan completed, there are a total of 141639667 lines, and it taken 215.80662393569946 seconds
Traceback (most recent call last):
  File "./jd.py", line 112, in <module>
    converter.start()
  File "./jd.py", line 79, in start
    self.connect_database()
  File "./jd.py", line 26, in connect_database
    self.database_connection = sqlite3.connect(self.database_path)
sqlite3.OperationalError: unable to open database file

**Comment by kallydev** [comment]
临时改下 py 脚本的代码里的参数吧。

```
if __name__ == '__main__':
    scanner = Scanner("这里写 database.db 的路径", "这里写 txt 文件的路径")
    scanner.start()
```

**Comment by creazytom** [comment]
> 临时改下 py 脚本的代码里的参数吧。
> 
> ```
> if __name__ == '__main__':
>     scanner = Scanner("这里写 database.db 的路径", "这里写 txt 文件的路径")
>     scanner.start()
> ```

改了改py路径，跑起来了

**Comment by creazytom** [comment]
> 临时改下 py 脚本的代码里的参数吧。
> 
> ```
> if __name__ == '__main__':
>     scanner = Scanner("这里写 database.db 的路径", "这里写 txt 文件的路径")
>     scanner.start()
> ```

老哥，等有空了把那个weibo库也做个导入吧

**Comment by kallydev** [comment]
> 改了改py路径，跑起来了

刚才我也把路径和文档改了。

> 老哥，等有空了把那个weibo库也做个导入吧

好的，我明天重构这些脚本，尽量做完善些。
